name: Generate README.md
description: CLI README.md generator for ShotGrid frameworks/engines/apps.

inputs:
  github_token:
    required: true
    description: GitHub secret token
  prepend:
    required: false
    description: Prepend an existing readme file after the name and description.
  append:
    required: false
    description: Append an existing readme file to the end.

runs:
  using: composite
  steps:
    - name: checkout repo content
      uses: actions/checkout@v4

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: info
      shell: bash
      run: echo action_path ${{ github.action_path }}

    - name: install python packages
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: execute py script
      shell: bash
      run: python tk-readme-generator.py "${{ github.action_path }}/info.yml" -o -p "${{ inputs.prepend }}" -a "${{ inputs.append }}"

    - name: commit files
      shell: bash
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git diff-index --quiet HEAD || (git commit -a -m "Update README.md" --allow-empty)

    - name: push changes
      uses: ad-m/github-push-action@v0.8.0
      with:
        github_token: ${{ inputs.github_token }}
        branch: ${{ github.ref }}