name: Update ShotGrid Readme
author: MaximumFX
description: Automatic README.md generator for ShotGrid frameworks/engines/apps and configurations.
branding:
  icon: book-open
  color: blue

inputs:
  github_token:
    required: true
    description: GitHub secret token
  infoFile:
    required: false
    description: The info.yml file
    default: info.yml
  prepend:
    required: false
    description: Filepath to an existing readme file to prepend after the name and description.
  append:
    required: false
    description: Filepath to an existing readme file to append to the end.
  mode:
    required: false
    description: Which generator should be used: 'general' for frameworks/engines/apps, 'config' for configurations.
    type: choice
    options:
      - general
      - config

runs:
  using: composite
  steps:
    - name: Checkout repo content
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Python packages
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ github.action_path }}/requirements.txt

    - name: Execute py script with automatic mode
      shell: bash
      if: "${{ inputs.mode == '' }}"
      run: python ${{ github.action_path }}/tk-readme-generator.py "${{ inputs.infoFile }}" -o -p "${{ inputs.prepend }}" -a "${{ inputs.append }}"

    - name: Execute py script with mode
      shell: bash
      if: "${{ inputs.mode != '' }}"
      run: python ${{ github.action_path }}/tk-readme-generator.py "${{ inputs.infoFile }}" -o -p "${{ inputs.prepend }}" -a "${{ inputs.append }}" -m ${{ inputs.mode }}

    - name: Commit files
      shell: bash
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git diff-index --quiet HEAD || (git commit -a -m "Update README.md" --allow-empty)

    - name: push changes
      uses: ad-m/github-push-action@v0.8.0
      with:
        github_token: ${{ inputs.github_token }}
        branch: ${{ github.ref }}
