name: Update README.md

on:
  push:
    paths:
      - "info.yml"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: MaximumFX/tk-readme-generator@v1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          mode: general
